"""
Insight Repository
"""

from typing import List, Optional
from sqlalchemy.orm import Session
from sqlalchemy import desc
from app.models.insight import Insight
from app.repositories.base import BaseRepository


class InsightRepository(BaseRepository[Insight]):
    def __init__(self, db: Session):
        super().__init__(Insight, db)

    def get_latest(self) -> Optional[Insight]:
        """Get the most recent insight"""
        return self.db.query(Insight).order_by(desc(Insight.created_at)).first()

    def get_recent(self, limit: int = 10) -> List[Insight]:
        """Get most recent insights"""
        return (
            self.db.query(Insight).order_by(desc(Insight.created_at)).limit(limit).all()
        )

    def get_by_job_id(self, job_id: str) -> Optional[Insight]:
        """Get insight generated by a specific job"""
        return self.db.query(Insight).filter(Insight.job_id == job_id).first()
