export { apiClient, default } from './client'
export { spoolsApi, default as spoolsService } from './spools'
export { colorsApi, default as colorsService } from './colors'
export { brandsApi, default as brandsService } from './brands'
export { materialsApi, default as materialsService } from './materials'
export { inventoryApi, default as inventoryService } from './inventory'
export { authApi } from './auth'
export { usersApi } from './users'
export { dashboardApi } from './dashboard'
export type { User, AuthResponse, LoginCredentials, RegisterCredentials } from './auth'
